##### Improting libraries #####
import pandas as pd
from snakemake.utils import min_version
min_version("7.6.1")
##### Improting libraries #####

##### Workflow guide #####
# RNA-Seq libraries
#   - Assess quality control
#   - Trim adapter sequences and filtering low quality reads - trimmomatic
#       - Map to reference genome
#       - Remove duplicates reads
#       - 
#       - Build up multiqc file
##### Workflow guide #####

##### Loading config file #####
configfile: "../config/config.yaml"
##### Loading config file #####

##### Loading phenodata file #####
phenodata = (
    pd.read_table(config["samples"], dtype={"Filename": str}, delimiter='\t')
    .set_index("Filename", drop=False)
    .sort_index()
)
##### Loading phenodata file #####

##### Getting all prefix from fastq.gz sample filename #####
SAMPLES = phenodata[["Filename"]].replace(".fastq.gz", "", regex=True).to_numpy().flatten()
##### Getting all prefix from fastq.gz sample filename #####

# TODO test recover sample names via wildcards
##### Getting all prefix from folder and using glob_wildcards
#SAMPLES = glob_wildcards("../resources/reads/{sample}.fastq.gz")
##### Getting all prefix from folder and using glob_wildcards

rule all:
    input:
        ### QC results ###
        "results/qc/multiqc_report.html",
        "results/qc/barplot_pca.png",
        "results/qc/scatterplot_pca.png",
        ### QC results ###

##### Loading rules #####
include: "rules/qc.smk" # PCA plot and check others QC processes as well
include: "rules/ref.smk" # Done
include: "rules/map-bowtie2.smk" # Done
include: "rules/featurecounts.smk" # Done
##### Loading rules #####


##### Execution #####
# snakemake --use-conda --cores 6 --latency-wait 20
#
# snakemake --dag | dot -Tsvg > dag.svg
# snakemake --dag | dot -Tpng > dag.png
##### Execution #####

##### If you face in the error message #####
# ModuleNotFoundError: No module named 'snakemake_wrapper_utils'
# You should install this module by this command line: pip install snakemake-wrapper-utils
##### If you face in the error message #####
